EXTRA = {
"coding": [
 "TypeError: Cannot read properties of undefined (reading 'map')",
 "Write a Python script to scrape titles from a webpage with BeautifulSoup",
 "How do I center a div with flexbox",
 "Implement a stack using two queues",
 "My React state update is not re-rendering the component",
 "Write a Java program to find duplicate elements in an array",
 "How do I catch exceptions in Python and log them",
 "Explain this Kubernetes YAML and why the pod is CrashLoopBackOff",
 "Write a function to validate an email address in JavaScript",
 "How do I add a foreign key constraint in PostgreSQL",
 "Convert this Python 2 code to Python 3",
 "Build a simple todo API with Express and MongoDB",
 "ModuleNotFoundError: No module named numpy even after pip install",
 "How to use useState with an array of objects",
 "Write a Swift function that sorts an array of structs by date",
 "What is the time complexity of this recursive function",
 "How do I mock an API call in Jest",
 "Fix my CSS, the navbar overlaps the content on mobile",
 "Write a Python class for a bank account with deposit and withdraw",
 "What does git rebase do and when should I use it",
 "Write a GraphQL schema for a blog with posts and comments",
 "How to make a Python script executable from the terminal",
 "Implement Dijkstra's algorithm in C++",
 "Why does my async function return a Promise instead of the value",
 "Write a PHP function that connects to MySQL using PDO",
 "Explain how a hash map works internally",
 "Write a Python generator that yields Fibonacci numbers",
 "How do I read environment variables in Node.js",
 "My SQL query is slow, how do I add and use an index",
 "Write an Arduino sketch to blink an LED every 500 ms",
 "How to serialize a dataclass to JSON in Python",
 "IndexError: list index out of range in my loop, why",
 "Set up a GitHub Actions workflow that runs pytest on push",
 "Write a Ruby method that counts word frequency in a string",
 "How do I upload a file to S3 using boto3",
 "Explain the difference between an interface and an abstract class",
 "Write a Python script to rename files based on their creation date",
 "How do I prevent SQL injection in my login form",
 "Create a responsive grid layout with Tailwind",
 "What is the difference between a process and a thread in an OS",
 "Write a Go HTTP server that returns hello world",
 "Why is my Python virtual environment not activating on Windows",
 "How do I implement pagination in a Django REST API",
 "Write a shell one-liner to count lines in all Python files",
 "Explain memory leaks in JavaScript closures",
],
"writing": [
 "Write a formal invitation for our college tech fest",
 "Draft a two-paragraph bio for my Twitter profile",
 "Write a heartfelt birthday message for my mom",
 "Create a compelling product launch email for our new sneaker",
 "Write a short horror story set in a hostel",
 "Rewrite this essay introduction to be more engaging",
 "Write an executive summary for our quarterly business report",
 "Compose a farewell message for a colleague who is leaving",
 "Write an Instagram caption for my graduation photo",
 "Draft a grant proposal abstract for a rural water project",
 "Write a 300-word article on the history of chai",
 "Help me write vows for my wedding",
 "Write a sales pitch script for cold calling gyms",
 "Write a children's rhyme about brushing teeth",
 "Turn this technical documentation into a friendly user guide",
 "Draft a sponsorship request letter for our robotics club",
 "Write a monologue for a villain who thinks he is the hero",
 "Compose an email declining a job offer politely",
 "Write a newsletter intro for our monthly community update",
 "Write a scene where two old friends meet after ten years",
 "Draft a professional out-of-office reply",
 "Write a book blurb for a fantasy novel about a librarian mage",
 "Write a letter to my future self",
 "Draft a statement of purpose for a PhD in computer science",
 "Write a funny best man speech",
 "Write a paragraph describing autumn in the mountains",
 "Create a tagline and slogan for a bicycle rental startup",
 "Write a complaint letter to the airline about lost luggage",
 "Draft a memo announcing the new work from home policy",
 "Write a sonnet about the ocean",
 "Write an FAQ section for our online course website",
 "Write a story in second person about waking up on Mars",
 "Draft a LinkedIn recommendation for my former manager",
 "Write a blog post titled ten lessons from my first startup",
 "Improve the flow and tone of this paragraph",
 "Write a podcast episode description about productivity habits",
 "Write a condolence message for a friend who lost her father",
 "Draft a pitch email to a journalist about our app",
 "Write a diary entry from the perspective of a street dog",
 "Write an essay arguing that homework should be abolished",
 "Compose a rap verse about debugging at 3 am",
 "Write a description for a YouTube video about budget travel",
 "Draft an agenda and opening remarks for our annual meeting",
 "Write a testimonial for my yoga instructor",
 "Write a cover letter for a marketing role at a fashion brand",
],
"search": [
 "Who is the current chief minister of Karnataka",
 "What is the latest iPhone model available in India",
 "When is Diwali this year",
 "What is the height of the Statue of Unity",
 "Latest updates on the Chandrayaan mission",
 "What is the price of gold today in Hyderabad",
 "Which country hosted the last G20 summit",
 "How many players are on a kabaddi team",
 "What is the official language of Brazil",
 "What is the current population of the world",
 "Who won the Oscar for best picture this year",
 "What is the Sensex at right now",
 "When does the IPL 2027 season start",
 "What is the longest river in Africa",
 "Which is the largest desert in the world",
 "Who invented the telephone",
 "What time zone is Dubai in",
 "Latest news about Tesla stock",
 "What year was Google founded",
 "What is the melting point of gold",
 "Who is the richest person in the world right now",
 "What are the top trending movies on Netflix India this week",
 "How many states does India have",
 "What is the deepest point in the ocean",
 "When was the Taj Mahal completed",
 "What is the currency of Vietnam",
 "Find the nearest passport office in Bangalore",
 "Recent developments in fusion energy research",
 "What is the national animal of Australia",
 "Who scored the most runs in the last cricket World Cup",
 "What is the fastest land animal",
 "What is the current status of the Bangalore suburban rail project",
 "How many bones are in the human body",
 "Who is the founder of Infosys",
 "What is the average temperature in Delhi in May",
 "What is the newest Marvel movie released",
 "Which planet has the most moons",
 "What is the current repo rate set by the RBI",
 "When did India gain independence",
 "Look up the ISBN of the book Sapiens",
 "What is the distance between Hyderabad and Bangalore by road",
 "What happened at the latest Apple WWDC keynote",
 "What is the chemical formula of caffeine",
 "Which team won the most recent Champions League final",
 "Are there any train strikes in Mumbai today",
],
"reasoning": [
 "If a shirt costs 800 after a 20 percent discount, what was the original price",
 "Explain why 0.999 repeating equals 1",
 "A lily pad doubles every day and covers the pond in 30 days, when did it cover half",
 "Which is the better strategy in rock paper scissors against a predictable opponent",
 "How many ways can 5 people sit in a row",
 "If I flip a fair coin 10 times, what is the expected number of heads",
 "Should our startup hire a senior engineer or two juniors, think through the trade-offs",
 "What is 17 times 23 without a calculator, show your working",
 "Why can't you divide a cake fairly among three people by cutting it once",
 "What is the logical fallacy in saying everyone believes it so it must be true",
 "If a car travels 150 km in 2.5 hours, what is the average speed",
 "Two dice are rolled, what is the probability the sum is 7",
 "Solve the system x plus y equals 10 and x minus y equals 4",
 "Think through whether it makes sense to buy an electric scooter for a 5 km commute",
 "Why does a heavier object not fall faster than a lighter one in a vacuum",
 "If you have a 3 litre and a 5 litre jug how do you measure exactly 4 litres",
 "What is the sum of the interior angles of a hexagon and why",
 "Argue for and against a universal basic income",
 "A snail climbs 3 metres a day and slips 2 at night, how long to climb a 10 metre wall",
 "Evaluate whether it is worth doing a masters right after undergrad",
 "Why is the Monty Hall answer counterintuitive to most people",
 "Explain the reasoning behind the prisoner's dilemma",
 "What number when doubled and added to 5 gives 19",
 "Estimate how many tennis balls fit in a bus",
 "If 3 workers build a wall in 6 days, how long do 9 workers take",
 "Is it logically valid to conclude it rained because the ground is wet",
 "Which is bigger, 2 to the power 100 or 100 to the power 20",
 "What is the minimum number of colours needed to colour any map",
 "Help me decide between studying abroad and staying in India for my degree",
 "How would you settle a dispute between two co-founders about equity",
 "Prove that the sum of two even numbers is even",
 "A shop offers 20 percent off then 10 percent off, is that the same as 30 percent off",
 "Reason out whether a ball thrown upward has zero acceleration at the top",
 "If the average of five numbers is 12 and one is removed leaving an average of 10, what was removed",
 "What is wrong with the argument that correlation proves causation",
 "Work out whether it's cheaper to take a cab daily or buy a bike over a year",
 "How many diagonals does a decagon have",
 "In how many years will a sum double at 10 percent simple interest",
 "Explain step by step how to decide which sorting algorithm to use",
 "If every person in a room shakes hands with everyone else and there are 45 handshakes, how many people",
 "Think about whether a company should open source its core product",
 "What is the remainder when 2 to the power 10 is divided by 7",
 "Explain Occam's razor with an example",
 "If it is 3 pm in London what time is it in Bangalore, reason it out",
 "Evaluate the argument that AI will take all jobs",
],
"multimodal": [
 "What is wrong with the plant in this photo",
 "Convert this screenshot of a table into markdown",
 "Look at the picture and tell me what time the clock shows",
 "What font is used in this image",
 "Describe the scene in this painting in detail",
 "Read the ingredients list from this photo of the packet",
 "Is the person in this image wearing a helmet",
 "Analyze the layout of this website screenshot",
 "What does this hand-drawn flowchart represent",
 "Identify the car brand from this logo image",
 "Explain the meme in this image",
 "Tell me what the graph in the screenshot is measuring",
 "How many chairs are visible in this room photo",
 "Extract the phone number from this business card photo",
 "Which cable in this photo goes to the router",
 "Grade this handwritten exam answer from the image",
 "What kind of rash is shown in this skin photo",
 "Describe the colours used in this poster",
 "Read the sign in this street photo and translate it",
 "Are these two images of the same person",
 "What's in this screenshot of my terminal error",
 "Look at this outfit photo and rate it out of ten",
 "What species of fish is in this aquarium picture",
 "Convert this photo of my notes into a bullet list",
 "Which piece is winning in this chessboard photo",
 "Identify the mountain range in this landscape photo",
 "What is the price on this shelf tag image",
 "What does the pie chart in this image show as the largest slice",
 "Describe the body language of the people in this meeting photo",
 "Is this photo of a bridge showing any structural damage",
 "Read the serial number from this photo of my laptop",
 "What is the total on this restaurant bill image",
 "Which of these two room photos looks tidier",
 "What is the animal in this blurry night photo",
 "Look at this sketch and tell me what building it is",
 "Suggest a caption for this sunset picture",
 "Read the temperature from this thermostat photo",
 "What year does this vintage car photo look like",
 "Identify the coin in this image and its country",
 "What is the score shown on this scoreboard picture",
 "Explain what is happening in this comic strip image",
 "Look at this MRI scan image and describe what you see",
 "Which fruit in this basket photo looks ripe",
 "What is written on the t-shirt in this picture",
 "Compare this before and after photo of the room",
],
}
